### PR TITLE
18 implement subadres

### PR DESCRIPTION
**Pull request by TalissaJoly**

### CODE REVIEW

**Comment by koenedaele** [comment]
Build currently failing with an actual error. Seems like a certain resource doesn't exist anymore.

**Comment by TalissaJoly** [comment]
Its failing because it doesn't have the latest version of crab yet. So the version it uses now doesn't have the subadres class and functions its trying to use.

**Comment by koenedaele** [comment]
Normally, it should work with 181d707dd3a5c0a042ef4abdb506fac0fcf9c7eb. Since this commit it should be pulling in the master of CRABpy.

**Comment by TalissaJoly** [comment]
There was a typo in the test url. It works now.

**Pull request merged**
